spring:
  application:
    name: ingestion-service
server:
    port: 8081
telemetry:
  collector:
    grpc:
      port: 4317
    enabled: true

logging:
  level:
    com.nishkarsh.ingestion_service.telemetry: INFO